### ISSUE TITLE
[Feature] Darkvision import

### ISSUE THREAD

**Issue by drober76** [zarmstrong/-hlo-to-fvtt-pf2-public#1]
**Describe the bug**
Darkvision does not map over

**To Reproduce**
Attempt to import character with darkvision

**Expected behavior**
Darkvision shows up in the imported sheet

**File ID this error occurred with**
download.php.JSON
 
**Additional context**
Darkvision appears in the export file under actor.1, items, abDarkvision

**Comment by zarmstrong** [comment]
Fix for this and low light vision in progress
