### ISSUE TITLE
[BUG] HLO Import Character unaccessable after import 

### ISSUE THREAD

**Issue by StevenVanDyk** [zarmstrong/-hlo-to-fvtt-pf2-public#10]
**Describe the bug**
Importing Character from HLO, creating new or updating existing cannot open char after 

import using 
$VlYdC3O~@P2#
You see the character does get renamed correctly while importing ..
the P is capitlized (small again in the Preview)

**Expected behavior**
Importing character

**Screenshots**

**File ID this error occurred with**
Please include the File ID produced by your conversion. This can be found by looking at the name of the file you downloaded. If you were unable to download a file, the File ID can be found on the error page.
 
**Additional context**
all modules, Worlds and game systems are fully updated

**Comment by zarmstrong** [comment]
I haven't been able to reproduce it, but I just updated the data sources to pf2e 1.14.0.  Try reimporting and letting me know if it works.

**Comment by StevenVanDyk** [comment]
ok working again .

Thanks

**Comment by zarmstrong** [comment]
Ok cool, maybe it was just the data sources
