### ISSUE TITLE
[BUG] Hitpoints don't correctly populate current/max

### ISSUE THREAD

**Issue by rchaining** [zarmstrong/-hlo-to-fvtt-pf2-public#11]
I am importing a character whose max hit points are 53, and the current hit points are 3. The tool returns a json with attributes.hp set as follows:

            "hp": {
                "value": 53,
                "min": 0,
                "max": 10,
                "temp": 0,
                "tempmax": 0,
                "details": ""
            }

Not sure why but herolab seems to render this with 15 max and current HP.

**To Reproduce**
1. Create character with a max HP of 53, and current HP of 3
2. Produce export data for that character on herolab, or import it directly using the native foundry module.
3. insect response JSON. The incorrect output is visible in both the foundry module and by copy/pasting the export-output from Herolab into the tool at https://www.pf2player.com/

**Expected behavior**
HP to align with herolab. Max is set to 53 and min is set to 3.

**Files**
HLO export: [HLO-Export-Gar'mak the Silver.txt](https://github.com/zarmstrong/hlo-to-fvtt-pf2-public/files/6956262/HLO-Export-Gar.mak.the.Silver.txt)
Tool output: [7NACBXeZV8h7hzJO.txt](https://github.com/zarmstrong/hlo-to-fvtt-pf2-public/files/6956270/7NACBXeZV8h7hzJO.txt)

**Comment by zarmstrong** [comment]
What's the element token for this character?

**Comment by rchaining** [comment]
$GlC9Yth~@P2#

**Comment by zarmstrong** [comment]
issue exists in fork only
