### ISSUE TITLE
[BUG] Champion/Desecrator import

### ISSUE THREAD

**Issue by Peter360** [zarmstrong/-hlo-to-fvtt-pf2-public#12]
Failed to import hero with using element token into new Actor

** Steps **
Retrieve token in hero lab
Create Actor in VTT
Click the HLO Import and paste the token

**Expected behavior**
Character import to VTT

**Screenshots**

![image](https://user-images.githubusercontent.com/3417759/129786581-269896fc-c6c8-429b-9433-7b495f30e6ca.png)

**File ID this error occurred with**
ID: zxTc6bcpuHbH2w7U
 
** other **
`
ConversionID: "1FABgSZoZvNVrCgx"
characterData: null
conversionData: "<h5>Conversion Completed</h5><br><strong>Note:</strong> You will have to manually equip any gear you want your character to wear. Be sure to go into your character in Foundry and equip any items you wish to be equipped.<br><strong>Note:</strong> Weapon and armor proficiencies are not exported from Herolab. The converter guesses your proficiences based on equipment you have on your PC. Please verify all proficiences are correct in Foundry.<br>"
`

**Comment by zarmstrong** [comment]
Can you post the element token please

**Comment by zarmstrong** [comment]
Fixed -- this was due to an error with deserator.

**Comment by Peter360** [comment]
thank you
