### ISSUE TITLE
[Feature] Class DC Proficiency

### ISSUE THREAD

**Issue by drober76** [zarmstrong/-hlo-to-fvtt-pf2-public#3]
**Describe the bug**
Class DC proficiency is not being imported, defaulting to "untrained"

**Expected behavior**
Maps to appropriate level of proficiency
 
**Additional context**
Class DC proficiency appears under the "clCLASSNAME" (e.g. "clRogue"), "ProfLevel" tag.

**Comment by zarmstrong** [comment]
Perfect, thanks. Fixed, but not yet deployed.
