### ISSUE TITLE
[BUG] Liberator class not detected properly

### ISSUE THREAD

**Issue by checkraze** [zarmstrong/-hlo-to-fvtt-pf2-public#6]
**Describe the bug**
The converter gives the error "Unable to determine class -- got liberator" when attempting to import conversion st4oJnbXIFwWk2ER. This results in a number of incorrect values including skill training levels for perception and class DC and max hit points.  

**To Reproduce**
1. Covert the character associated with conversion st4oJnbXIFwWk2ER
2. Import the resulting st4oJnbXIFwWk2ER.json into Foundry VTT
3. Open the character sheet and the values above are not imported correctly. 

**Expected behavior**
Class is detected on conversion and the values dependent on class are set properly. 

**File ID this error occurred with**
st4oJnbXIFwWk2ER.json
 
**Additional context**
Foundry 0.7.8, PF2e system 1.10.17.2355, Herolab build F5FE3E4

**Comment by zarmstrong** [comment]
fixed

**Comment by checkraze** [comment]
Thanks so much for the quick response! Loving the tool.

**Comment by zarmstrong** [comment]
No worries! If you have any really complex builds that are missing things, please shoot them over to me so I can work on getting the tool to cover more cases.  Keep the reports coming!
