### ISSUE TITLE
[BUG] Fencer Swashbuckler style not detected

### ISSUE THREAD

**Issue by checkraze** [zarmstrong/-hlo-to-fvtt-pf2-public#7]
**Describe the bug**
Fencer Swashbuckler style not detected. Gives the error "The following feats/abilities were not found and must be added manually: Fencer"

**To Reproduce**
1. Covert the character associated with conversion iFa7FFZRHOmYZeLb
2. Import the resulting iFa7FFZRHOmYZeLb.json into Foundry VTT
3. Open the character sheet and the values above are not imported correctly.

**Expected behavior**
Fencer style is detected and set in the imported sheet. 

**File ID this error occurred with**
iFa7FFZRHOmYZeLb

**Additional context**
Foundry 0.7.8, PF2e system 1.10.17.2355, Herolab build F5FE3E4

**Comment by zarmstrong** [comment]
Thanks, fixed in 0.10.2, which is now live
