### ISSUE TITLE
[BUG] 1 byte export

### ISSUE THREAD

**Issue by Nuku** [zarmstrong/-hlo-to-fvtt-pf2-public#8]
I am trying to import [removed json as it wasn't needed --zarmstrong]

It converts to a 1 byte file. Other characters have the same fate.

**Comment by zarmstrong** [comment]
I quite literally just fixed the bug causing this :)  Can you try again?  

Also, it would be super helpful if you could join my HLO campaign and import this PC into it.  The issue stems from HLO not exporting a land speed with the character. This is something I hadn't seen before today, so I wonder if something broke on their side. But without seeing your character in HLO, it's impossible for me to tell.  

You can join the campaign with invite code: **NB3CQE83**

**Comment by Nuku** [comment]
Ah ha, this was for custom ancestries. That would explain it. Thank you!

**Comment by zarmstrong** [comment]
Ah interesting, thanks for letting me know
